In [1]:
import pandas as pd

In [2]:
folder_location = '/Users/pyuvraj/CCPP/data_for_profit_from_stock/stock_per_category'
file_name = 'all_stocks_data_with_ranking_v3.csv'
database = pd.read_csv(folder_location + '/' + file_name)

In [5]:
database

,Unnamed: 0,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,...,stock_symbol,overall_profit,2017_value,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit
0,0,AAPL,Apple Inc. Common Stock,$146.14,-0.70,-0.477%,2.533679e+12,United States,1980.0,54087029,...,AAPL,180.408388,150.551075,189.053427,208.255952,293.318412,43.924768,25.574278,10.157195,40.845152
1,1,ADBE,Adobe Inc. Common Stock,$631.38,-0.70,-0.111%,3.007894e+11,United States,1986.0,1127719,...,ADBE,250.783152,143.996136,235.037450,279.322818,341.399841,47.953843,63.224831,18.841835,22.224114
2,2,ADSK,Autodesk Inc. Common Stock,$332.77,3.95,1.201%,7.321383e+10,United States,NaN,856872,...,ADSK,196.197882,102.460638,132.064701,158.893175,182.828730,65.994829,28.893109,20.314644,15.063929
3,3,ADUS,Addus HomeCare Corporation Common Stock,$91.40,1.98,2.214%,1.453574e+09,United States,2009.0,116726,...,ADUS,272.556161,34.741833,56.669602,75.761905,86.155238,50.232117,63.116327,33.690555,13.718416
4,4,AJG,Arthur J. Gallagher & Co. Common Stock,$139.06,0.44,0.317%,2.875066e+10,United States,NaN,870658,...,AJG,105.057566,58.599522,70.396614,85.598691,95.463492,25.872992,20.131720,21.594898,11.524477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,142,WNS,WNS (Holdings) Limited Sponsored ADR (Jersey),$82.40,1.39,1.716%,4.005885e+09,India,2006.0,105645,...,WNS,121.858826,33.686335,48.085139,57.504564,63.700159,17.324836,42.743756,19.589054,10.774093
143,143,WST,West Pharmaceutical Services Inc. Common Stock,$427.49,1.83,0.43%,3.162532e+10,United States,NaN,285491,...,WST,111.144174,91.061195,101.587131,126.632024,153.855397,24.968257,11.559189,24.653607,21.498016
144,144,ZNGA,Zynga Inc. Class A Common Stock,$7.99,-1.78,-18.219%,8.699215e+09,United States,2011.0,101409942,...,ZNGA,153.980809,3.390637,3.857729,5.734762,6.575079,30.972844,13.775924,48.656419,14.653048
145,145,ZTS,Zoetis Inc. Class A Common Stock,$201.88,-1.96,-0.962%,9.584590e+10,United States,2013.0,1282630,...,ZTS,174.603291,61.130040,85.541992,110.373135,131.353651,27.796296,39.934462,29.028016,19.008716
146,146,ZYXI,Zynex Inc. Common Stock,$14.89,0.35,2.407%,5.175822e+08,United States,NaN,1467543,...,ZYXI,3520.182472,1.117171,3.383506,7.544246,10.705397,277.787397,202.863664,122.971264,41.901481

In [10]:
database.sort_values(['overall_profit', '2020_profit'], ascending=[0, 0])

,Unnamed: 0,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,...,stock_symbol,overall_profit,2017_value,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit
61,61,FRHC,Freedom Holding Corp. Common Stock,$64.56,0.22,0.342%,3.773094e+09,Kazakhstan,NaN,243351,...,FRHC,12461.223569,0.982074,6.989639,10.965480,15.030476,720.735629,611.722408,56.881934,37.070843
52,52,EQX,Equinox Gold Corp. Common Shares,$6.33,-0.23,-3.506%,1.891882e+09,Canada,NaN,2760927,...,EQX,4472.904954,1.052000,1.221364,2.830567,7.865397,511.627885,16.099205,131.754686,177.873497
146,146,ZYXI,Zynex Inc. Common Stock,$14.89,0.35,2.407%,5.175822e+08,United States,NaN,1467543,...,ZYXI,3520.182472,1.117171,3.383506,7.544246,10.705397,277.787397,202.863664,122.971264,41.901481
55,55,FATE,Fate Therapeutics Inc. Common Stock,$95.42,-0.12,-0.126%,8.972893e+09,United States,2013.0,824039,...,FATE,1023.208033,3.838645,11.604861,17.227698,25.208889,71.034804,202.316555,48.452438,46.327665
47,47,EHTH,eHealth Inc. Common Stock,$51.15,2.11,4.303%,1.338046e+09,United States,2006.0,507654,...,EHTH,942.476416,17.589323,24.024462,72.786667,114.942540,59.527136,36.585488,202.968974,57.917026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21,21,BKI,Black Knight Inc. Common Stock,$78.44,-2.47,-3.053%,1.228479e+10,NaN,2017.0,777277,...,BKI,86.692238,41.204382,49.850080,57.896627,65.358730,17.697183,20.982470,16.141493,12.888666
70,70,J,Jacobs Engineering Group Inc. Common Stock,$128.89,0.15,0.117%,1.679622e+10,United States,NaN,604801,...,J,85.572987,56.741195,66.560319,81.194008,90.728254,16.056825,17.305105,21.985606,11.742548
31,31,CDMO,Avid Bioservices Inc. Common Stock,$26.01,0.10,0.386%,1.589150e+09,United States,NaN,224477,...,CDMO,84.375645,3.872908,4.433028,5.076706,6.028571,18.447627,14.462504,14.520063,18.749658
106,106,PLD,Prologis Inc. Common Stock,$129.71,-0.74,-0.567%,9.588825e+10,United States,NaN,3207789,...,PLD,82.428948,58.400279,64.273626,79.065079,87.136825,22.266349,10.057052,23.013255,10.208990
72,72,KSU,Kansas City Southern Common Stock,$271.77,0.05,0.018%,2.472147e+10,United States,NaN,530392,...,KSU,72.673339,97.794422,108.139681,124.990397,152.100476,11.021937,10.578578,15.582361,21.689730

In [12]:
print(database)

     Unnamed: 0 Symbol                                            Name  \
0             0   AAPL                         Apple Inc. Common Stock
1             1   ADBE                         Adobe Inc. Common Stock
2             2   ADSK                      Autodesk Inc. Common Stock
3             3   ADUS         Addus HomeCare Corporation Common Stock
4             4    AJG          Arthur J. Gallagher & Co. Common Stock
..          ...    ...                                             ...
142         142    WNS   WNS (Holdings) Limited Sponsored ADR (Jersey)
143         143    WST  West Pharmaceutical Services Inc. Common Stock
144         144   ZNGA                 Zynga Inc. Class A Common Stock
145         145    ZTS                Zoetis Inc. Class A Common Stock
146         146   ZYXI                         Zynex Inc. Common Stock

    Last Sale  Net Change  % Change    Market Cap        Country  IPO Year  \
0     $146.14       -0.70   -0.477%  2.533679e+12  United States    1980.0
1     $631.38       -0.70   -0.111%  3.007894e+11  United States    1986.0
2     $332.77        3.95    1.201%  7.321383e+10  United States       NaN
3      $91.40        1.98    2.214%  1.453574e+09  United States    2009.0
4     $139.06        0.44    0.317%  2.875066e+10  United States       NaN
..        ...         ...       ...           ...            ...       ...
142    $82.40        1.39    1.716%  4.005885e+09          India    2006.0
143   $427.49        1.83     0.43%  3.162532e+10  United States       NaN
144     $7.99       -1.78  -18.219%  8.699215e+09  United States    2011.0
145   $201.88       -1.96   -0.962%  9.584590e+10  United States    2013.0
146    $14.89        0.35    2.407%  5.175822e+08  United States       NaN

        Volume  ... stock_symbol overall_profit  2017_value  2018_value  \
0     54087029  ...         AAPL     180.408388  150.551075  189.053427
1      1127719  ...         ADBE     250.783152  143.996136  235.037450
2       856872  ...         ADSK     196.197882  102.460638  132.064701
3       116726  ...         ADUS     272.556161   34.741833   56.669602
4       870658  ...          AJG     105.057566   58.599522   70.396614
..         ...  ...          ...            ...         ...         ...
142     105645  ...          WNS     121.858826   33.686335   48.085139
143     285491  ...          WST     111.144174   91.061195  101.587131
144  101409942  ...         ZNGA     153.980809    3.390637    3.857729
145    1282630  ...          ZTS     174.603291   61.130040   85.541992
146    1467543  ...         ZYXI    3520.182472    1.117171    3.383506

     2019_value  2020_value  2017_profit  2018_profit  2019_profit  \
0    208.255952  293.318412    43.924768    25.574278    10.157195
1    279.322818  341.399841    47.953843    63.224831    18.841835
2    158.893175  182.828730    65.994829    28.893109    20.314644
3     75.761905   86.155238    50.232117    63.116327    33.690555
4     85.598691   95.463492    25.872992    20.131720    21.594898
..          ...         ...          ...          ...          ...
142   57.504564   63.700159    17.324836    42.743756    19.589054
143  126.632024  153.855397    24.968257    11.559189    24.653607
144    5.734762    6.575079    30.972844    13.775924    48.656419
145  110.373135  131.353651    27.796296    39.934462    29.028016
146    7.544246   10.705397   277.787397   202.863664   122.971264

     2020_profit
0      40.845152
1      22.224114
2      15.063929
3      13.718416
4      11.524477
..           ...
142    10.774093
143    21.498016
144    14.653048
145    19.008716
146    41.901481

[147 rows x 22 columns]

In [17]:
database.groupby(['Sector']).mean()

,Unnamed: 0,Net Change,Market Cap,IPO Year,Volume,overall_profit,2017_value,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit
Sector,,,,,,,,,,,,,,
Basic Industries,60.833333,0.630000,1.432250e+10,2002.500000,6.514477e+05,874.107844,68.331861,82.593876,99.736771,111.861151,108.693710,28.680975,43.103500,45.602078
Capital Goods,80.647059,-0.456471,3.489169e+10,2002.666667,4.492140e+05,164.864620,62.062203,79.183408,97.735021,114.190738,39.279448,27.249830,25.797492,18.057197
Consumer Durables,67.000000,11.320000,2.619761e+10,2010.000000,7.604540e+05,183.187874,41.059203,51.144104,69.911151,102.673810,13.246684,24.561851,36.694449,46.863281
Consumer Non-Durables,66.500000,-1.580000,2.090642e+10,2004.000000,1.756655e+05,171.167177,104.534163,147.995139,181.887222,211.057381,32.291152,43.032917,22.896453,16.044398
Consumer Services,73.588235,-1.890588,2.930702e+10,2005.416667,5.605236e+05,164.119052,110.774331,134.572949,190.727967,236.088562,31.246332,27.276554,31.973476,18.083712
Energy,61.000000,0.220000,3.773094e+09,NaN,2.433510e+05,12461.223569,0.982074,6.989639,10.965480,15.030476,720.735629,611.722408,56.881934,37.070843
Finance,50.444444,1.035556,2.576440e+10,2012.250000,8.051781e+05,240.420646,53.479781,66.287395,88.712070,108.272646,31.099284,24.898231,47.891262,25.622595
Health Care,83.833333,-1.245333,1.362651e+10,2009.210526,5.384193e+05,433.059488,46.159975,66.089817,87.770257,112.710294,51.528931,60.959377,42.834927,30.058811
Miscellaneous,75.357143,0.458571,9.287430e+10,1999.750000,5.730004e+06,206.628106,91.252266,127.394183,170.639034,205.512211,39.304133,39.237058,29.523716,21.550270
Public Utilities,50.666667,0.090000,5.424283e+10,1998.000000,1.631336e+06,321.672704,54.559854,67.036228,88.122725,107.466666,49.364746,38.669521,55.553634,26.176668
Technology,69.711111,0.101111,1.489097e+11,2005.147059,7.787259e+06,292.151924,60.213556,85.338189,113.714959,141.926995,42.087166,49.288482,41.547652,25.322089
Transportation,85.000000,0.290000,2.817367e+10,1991.000000,3.966660e+05,131.698279,81.973586,102.065339,115.341270,142.420080,27.954038,27.841826,12.844335,23.640301

In [20]:
folder_location = '/Users/pyuvraj/CCPP/data_for_profit_from_stock/stock_per_category'
file_name = 'all_stocks_data_with_ranking_v2.csv'
database = pd.read_csv(folder_location + '/' + file_name)

In [21]:
database.groupby(['Sector']).mean()

,Unnamed: 0,Net Change,Market Cap,IPO Year,Volume,overall_profit,2017_value,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit
Sector,,,,,,,,,,,,,,
Basic Industries,2561.044053,0.417345,8.819153e+09,2009.111111,1.571309e+06,27.431543,34.827733,35.501237,32.392155,30.190584,31.150708,3.371106,-8.579277,-9.705734
Capital Goods,2437.509284,-0.053217,1.211010e+10,2006.680000,9.084249e+05,332.833235,56.024850,57.308874,56.725874,57.852884,32.725309,7.014943,222.155056,-8.046842
Consumer Durables,2243.011364,0.297510,5.825538e+09,2009.325581,9.966160e+05,57.006401,35.068344,33.779021,29.810139,28.266592,19.425538,35.343381,-8.955660,286.806317
Consumer Non-Durables,2501.846995,0.219056,1.834930e+10,2007.558824,1.277788e+06,9.460892,76.796266,55.279438,47.913873,45.868617,9.419416,8.352419,-2.934377,-12.230921
Consumer Services,2352.481301,-0.139359,1.374150e+10,2008.777049,1.197631e+06,831.025781,80.669372,48.380000,47.398017,46.921290,285.213767,58.106190,-1.926224,-9.359792
Energy,2520.412844,0.179668,9.148919e+09,2012.171429,1.729674e+06,191.756413,1422.455245,151.406857,25.742874,18.538284,180.415604,23.151310,-24.580894,-34.107782
Finance,2294.816327,0.526547,5.519997e+09,2007.310292,7.536454e+05,367.609962,50.146713,34.808334,33.293918,31.050212,290.035655,134.663311,0.593052,-5.785963
Health Care,2295.068096,-0.393047,9.091526e+09,2012.747454,1.169917e+06,60.114272,51.118303,38.808896,32.161034,32.231236,24.365708,38.795228,-8.149140,0.746144
Miscellaneous,2447.111842,-0.047863,1.907260e+10,2009.453333,1.782940e+06,123.809479,45.778290,49.386449,52.094263,53.335044,20.572540,19.275320,158.647243,-8.489056
Public Utilities,2407.915842,-0.072972,1.288708e+10,2011.960526,1.243895e+06,3994.300153,183.272855,151.377289,78.609634,37.438149,16.120919,1.119734,3.341372,-4.070284
Technology,2499.418966,-0.097921,3.226487e+10,2007.868020,1.912859e+06,433.129929,224.200360,49.075056,48.162414,50.198955,35.076776,67.797290,126.614194,-4.278555
Transportation,2491.377358,-0.093345,9.973542e+09,2006.410714,1.627675e+06,10.618062,20344.958094,59.919058,54.772347,51.264008,17.670864,3.396488,-9.187772,-10.558588

In [30]:
database[database.Sector == 'Consumer Durables'].sort_values(by=['overall_profit'], ascending=False)

,Unnamed: 0,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,...,stock_symbol,overall_profit,2017_value,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit
4545,4545,VRT,Vertiv Holdings LLC Class A Common Stock,$27.26,-0.09,-0.329%,9.607183e+09,United States,2018.0,2168193,...,VRT,2730.747208,0.454602,8.340419,10.155528,10.989365,17.100686,1734.665674,21.762795,8.210674
518,518,BE,Bloom Energy Corporation Class A Common Stock,$21.68,0.34,1.593%,3.737412e+09,NaN,2018.0,2755893,...,BE,1308.827928,1.766853,16.988573,9.156746,8.416349,195.756653,861.516171,-46.100559,-8.085807
857,857,CGC,Canopy Growth Corporation Common Shares,$19.15,0.01,0.052%,7.529144e+09,Canada,NaN,7271150,...,CGC,467.849604,8.920641,31.569048,34.416429,18.697778,170.918971,253.887645,9.019533,-45.671941
3179,3179,OESX,Orion Energy Systems Inc. Common Stock,$5.01,-0.04,-0.792%,1.553010e+08,United States,2015.0,108492,...,OESX,188.285263,1.364263,0.886335,2.208571,4.363175,-9.859921,-35.031977,149.180307,97.556417
1875,1875,GNRC,Generac Holdlings Inc. Common Stock,$415.04,11.32,2.804%,2.619761e+10,United States,2010.0,760454,...,GNRC,183.187874,41.059203,51.144104,69.911151,102.673810,13.246684,24.561851,36.694449,46.863281
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2062,2062,HOTH,Hoth Therapeutics Inc. Common Stock,$1.30,-0.04,-2.985%,3.103317e+07,United States,2019.0,330627,...,HOTH,NaN,NaN,NaN,5.269416,4.385397,NaN,NaN,NaN,-16.776421
4152,4152,TBIO,Translate Bio Inc. Common Stock,$37.74,-0.01,-0.026%,2.852643e+09,United States,2018.0,5985498,...,TBIO,NaN,NaN,9.525000,9.232877,8.194286,NaN,NaN,-3.066908,-11.248837
4201,4201,TFFP,TFF Pharmaceuticals Inc. Common Stock,$8.00,0.07,0.883%,2.029142e+08,United States,2019.0,67216,...,TFFP,NaN,NaN,NaN,5.131109,4.743508,NaN,NaN,NaN,-7.553939
4239,4239,TLRY,Tilray Inc. Class 2 Common Stock,$14.42,-0.05,-0.346%,6.433582e+09,Canada,2018.0,11635870,...,TLRY,NaN,NaN,89.371930,44.920913,13.836032,NaN,NaN,-49.737112,-69.199130
4496,4496,VIOT,Viomi Technology Co. Ltd American Depositary S...,$5.62,0.07,1.261%,3.920534e+08,China,2018.0,199532,...,VIOT,NaN,NaN,8.499403,9.194762,6.728889,NaN,NaN,8.181267,-26.818237

In [31]:
database.sort_values(by=['overall_profit'], ascending=False)

,Unnamed: 0,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,...,stock_symbol,overall_profit,2017_value,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit
1310,1310,DTW,DTE Energy Company 2017 Series E 5.25% Junior ...,$26.38,-0.0400,-0.151%,0.000000e+00,United States,2017.0,81079,...,DTW,702998.163049,NaN,23.734943,25.799869,25.474571,NaN,NaN,8.699939,-1.260850
3261,3261,OSW,OneSpaWorld Holdings Limited Common Shares,$10.46,0.0200,0.192%,9.462879e+08,Bahamas,NaN,221677,...,OSW,302509.677583,4.699119,9.745223,14.034683,11.898730,119408.449300,107.384062,44.016019,-15.219100
2372,2372,JPT,Nuveen Preferred and Income 2022 Term Fund Com...,$25.35,0.0450,0.178%,1.734212e+08,United States,2017.0,11462,...,JPT,277270.298639,24.107894,23.323657,23.828984,23.460905,284919.429825,-3.253028,2.166585,-1.544671
567,567,BILL,Bill.com Holdings Inc. Common Stock,$202.92,-6.0000,-2.872%,1.895153e+10,NaN,2019.0,848442,...,BILL,100261.795534,2.875000,NaN,37.970000,47.069683,6030.063911,NaN,NaN,23.965453
4316,4316,TT,Trane Technologies plc,$197.00,1.5700,0.803%,4.711206e+10,Ireland,NaN,825592,...,TT,86692.639232,0.168000,0.168000,121.586505,120.765238,20.739738,0.000000,72272.920531,-0.675459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4752,4752,ZLAB,Zai Lab Limited American Depositary Shares,$148.94,-0.9200,-0.614%,1.122643e+10,China,2017.0,475683,...,ZLAB,NaN,26.744648,21.110618,32.077540,52.069048,NaN,-21.066011,51.949793,62.322448
4753,4753,ZM,Zoom Video Communications Inc. Class A Common ...,$383.47,-15.2100,-3.815%,1.138760e+11,United States,2019.0,3088163,...,ZM,NaN,NaN,NaN,80.239382,99.284603,NaN,NaN,NaN,23.735504
4756,4756,ZOM,Zomedica Corp. Common Shares,$0.59,-0.0034,-0.573%,5.769102e+08,United States,2017.0,13835397,...,ZOM,NaN,2.220889,1.945263,0.453567,0.229317,NaN,-12.410614,-76.683488,-49.441378
4757,4757,ZS,Zscaler Inc. Common Stock,$242.05,-5.6200,-2.269%,3.315771e+10,United States,2018.0,1405866,...,ZS,NaN,NaN,35.851425,60.744544,55.155000,NaN,NaN,69.434112,-9.201721
4763,4763,ZVO,Zovio Inc. Common Stock,$2.34,0.0700,3.084%,7.819756e+07,United States,NaN,93634,...,ZVO,NaN,NaN,NaN,3.150000,1.653810,NaN,NaN,NaN,-47.498110

In [37]:
database['overall_profit_column_avg'] = (database['2017_profit'] + database['2018_profit'] + database['2019_profit'] + database['2020_profit']) / 4

In [38]:
database.sort_values(by=['overall_profit_column_avg'], ascending=False)

,Unnamed: 0,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,...,2018_value,2019_value,2020_value,2017_profit,2018_profit,2019_profit,2020_profit,overall_profit_column,overall_profit_column_2019_2020,overall_profit_column_avg
2372,2372,JPT,Nuveen Preferred and Income 2022 Term Fund Com...,$25.35,0.0450,0.178%,1.734212e+08,United States,2017.0,11462,...,23.323657,23.828984,23.460905,284919.429825,-3.253028,2.166585,-1.544671,284916.798711,0.621914,71229.199678
3261,3261,OSW,OneSpaWorld Holdings Limited Common Shares,$10.46,0.0200,0.192%,9.462879e+08,Bahamas,NaN,221677,...,9.745223,14.034683,11.898730,119408.449300,107.384062,44.016019,-15.219100,119544.630281,28.796919,29886.157570
4592,4592,WEI,Weidai Ltd. American depositary shares each r...,$1.04,0.0400,4.00%,7.327991e+07,Cayman Islands,2018.0,1243027,...,5.845980,8.285317,2.095714,0.000000,116819.610067,41.726741,-74.705685,116786.631123,-32.978944,29196.657781
4316,4316,TT,Trane Technologies plc,$197.00,1.5700,0.803%,4.711206e+10,Ireland,NaN,825592,...,0.168000,121.586505,120.765238,20.739738,0.000000,72272.920531,-0.675459,72292.984810,72272.245072,18073.246203
4002,4002,SPT,Sprout Social Inc Class A Common Stock,$104.99,-0.5300,-0.502%,5.648911e+09,United States,2019.0,361518,...,0.025000,16.239167,18.161587,-0.131200,-4.924241,64856.665978,11.838173,64863.448710,64868.504151,16215.862178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4752,4752,ZLAB,Zai Lab Limited American Depositary Shares,$148.94,-0.9200,-0.614%,1.122643e+10,China,2017.0,475683,...,21.110618,32.077540,52.069048,NaN,-21.066011,51.949793,62.322448,NaN,114.272241,NaN
4753,4753,ZM,Zoom Video Communications Inc. Class A Common ...,$383.47,-15.2100,-3.815%,1.138760e+11,United States,2019.0,3088163,...,NaN,80.239382,99.284603,NaN,NaN,NaN,23.735504,NaN,NaN,NaN
4756,4756,ZOM,Zomedica Corp. Common Shares,$0.59,-0.0034,-0.573%,5.769102e+08,United States,2017.0,13835397,...,1.945263,0.453567,0.229317,NaN,-12.410614,-76.683488,-49.441378,NaN,-126.124866,NaN
4757,4757,ZS,Zscaler Inc. Common Stock,$242.05,-5.6200,-2.269%,3.315771e+10,United States,2018.0,1405866,...,35.851425,60.744544,55.155000,NaN,NaN,69.434112,-9.201721,NaN,60.232391,NaN
4763,4763,ZVO,Zovio Inc. Common Stock,$2.34,0.0700,3.084%,7.819756e+07,United States,NaN,93634,...,NaN,3.150000,1.653810,NaN,NaN,NaN,-47.498110,NaN,NaN,NaN

In [40]:
database.groupby(by='overall_profit').nlargest(3)

AttributeError: 'DataFrameGroupBy' object has no attribute 'nlargest'

In [46]:
temp = database.groupby('Sector')['overall_profit'].nlargest(3)

In [48]:
print(temp)

Sector
Basic Industries       1467      4472.904954
                       2861       585.417608
                       236        290.887025
Capital Goods          4316     86692.639232
                       3511     16242.328958
                       1431      1890.110599
Consumer Durables      4545      2730.747208
                       518       1308.827928
                       857        467.849604
Consumer Non-Durables  1072       247.703663
                       2473       230.777810
                       1702       230.585864
Consumer Services      3261    302509.677583
                       1825     68420.554764
                       3608     33139.198973
Energy                 2739     26543.351938
                       1719     12461.223569
                       672       2407.046333
Finance                2372    277270.298639
                       4592     41814.286566
                       980      19286.675934
Health Care            1459      8449.206319
                       4765      3520.182472
                       3886      2257.616451
Miscellaneous          2134      8488.761878
                       3095       729.531994
                       869        561.449371
Public Utilities       1310    702998.163049
                       1161       466.057883
                       400        389.097163
Technology             567     100261.795534
                       4002     68878.448323
                       4116      5002.544918
Transportation         1886       406.086927
                       367        257.189510
                       3765       194.145843
Name: overall_profit, dtype: float64

In [53]:
from pandas.io import sql
import MySQLdb

In [58]:
con = MySQLdb.connect(host="localhost", user="root", passwd="", db="profit_from_stock")

In [60]:
database.to_sql(con=con, name="profit_for_stock_full_database", if_exists='replace')

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:2605: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(

DatabaseError: Execution failed on sql 'SELECT name FROM sqlite_master WHERE type='table' AND name=?;': not all arguments converted during bytes formatting

In [61]:
from sqlalchemy import create_engine

In [65]:
engine = create_engine('mysql+mysqlconnector://root:@localhost/profit_from_stock')

In [66]:
database.to_sql(con=engine, name="profit_for_stock_full_database", if_exists='replace')